-- LAB 03
-- Doãn Hoàng Sơn |	22127365
-- Võ Hữu Tuấn    |	22127439


--  a. tạo Database có tên QLSVNhom
USE MASTER
GO

IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'QLSVNhom')
BEGIN
    CREATE DATABASE QLSVNhom;
END;

GO

USE QLSVNhom;

GO

-- b. tạo các Table SINHVIEN, NHANVIEN, LOP, HOCPHAN, BANGDIEM

-- Tạo bảng SINHVIEN
CREATE TABLE SINHVIEN (
    MASV VARCHAR(20) PRIMARY KEY,
    HOTEN NVARCHAR(100) NOT NULL,
    NGAYSINH DATETIME,
    DIACHI NVARCHAR(200),
    MALOP VARCHAR(20),
    TENDN NVARCHAR(100) UNIQUE NOT NULL,
    MATKHAU VARBINARY(MAX) NOT NULL
);

GO

-- Tạo bảng NHANVIEN
CREATE TABLE NHANVIEN (
    MANV VARCHAR(20) PRIMARY KEY,
    HOTEN NVARCHAR(100) NOT NULL,
    EMAIL VARCHAR(20),
    LUONG VARBINARY(MAX),
    TENDN NVARCHAR(100) UNIQUE NOT NULL,
    MATKHAU VARBINARY(MAX) NOT NULL,
    PUBKEY VARCHAR(20) NOT NULL
);

GO

-- Tạo bảng LOP
CREATE TABLE LOP (
    MALOP VARCHAR(20) PRIMARY KEY,
    TENLOP NVARCHAR(100) NOT NULL,
    MANV VARCHAR(20),
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

GO

-- Tạo bảng HOCPHAN
CREATE TABLE HOCPHAN (
    MAHP VARCHAR(20) PRIMARY KEY,
    TENHP NVARCHAR(100) NOT NULL,
    SOTC INT
);

GO

-- Tạo bảng BANGDIEM
CREATE TABLE BANGDIEM (
    MASV VARCHAR(20),
    MAHP VARCHAR(20),
    DIEMTHI VARBINARY(MAX),
    PRIMARY KEY (MASV, MAHP),
    FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV),
    FOREIGN KEY (MAHP) REFERENCES HOCPHAN(MAHP)
);

GO

-- c. Viết các Stored procedure

-- i. SP_INS_PUBLIC_NHANVIEN
-- Stored dùng để thêm mới dữ liệu (Insert) vào table NHANVIEN
CREATE PROCEDURE SP_INS_PUBLIC_NHANVIEN
    @MANV VARCHAR(20),
    @HOTEN NVARCHAR(100),
    @EMAIL VARCHAR(20),
    @LUONGCB FLOAT,
    @TENDN NVARCHAR(100),
    @MK NVARCHAR(100)
AS
BEGIN
    DECLARE @HASHED_MK VARBINARY(MAX)
    DECLARE @ENCRYPTED_LUONG VARBINARY(MAX)

    -- Mã hóa mật khẩu bằng SHA1
    SET @HASHED_MK = HASHBYTES('SHA1', @MK)

    -- Mã hóa lương bằng RSA
    SET @ENCRYPTED_LUONG = ENCRYPTBYKEY(KEY_GUID('RSA_512'), CAST(@LUONGCB AS NVARCHAR))

    -- Thêm nhân viên vào bảng
    INSERT INTO NHANVIEN (MANV, HOTEN, EMAIL, LUONG, TENDN, MATKHAU, PUBKEY)
    VALUES (@MANV, @HOTEN, @EMAIL, @ENCRYPTED_LUONG, @TENDN, @HASHED_MK, @MANV) -- PUBKEY = MANV
END

GO

-- ii. SP_SEL_PUBLIC_NHANVIEN
-- Stored dùng để truy vấn dữ liệu nhân viên (NHANVIEN)
CREATE PROCEDURE SP_SEL_PUBLIC_NHANVIEN
    @TENDN NVARCHAR(100),
    @MK NVARCHAR(100)
AS
BEGIN
    DECLARE @MANV VARCHAR(20)
    DECLARE @LUONGCB NVARCHAR(100)

    -- Xác thực mật khẩu
    SELECT @MANV = MANV
    FROM NHANVIEN
    WHERE TENDN = @TENDN AND MATKHAU = HASHBYTES('SHA1', @MK)

    IF @MANV IS NULL
    BEGIN
        PRINT 'Sai tài kho?n ho?c m?t kh?u'
        RETURN
    END

    -- Giải mã lương
	SELECT MANV, HOTEN, EMAIL,
		   CONVERT(FLOAT, CAST(DECRYPTBYKEY(LUONG) AS NVARCHAR(100))) AS LUONGCB
	FROM NHANVIEN
	WHERE MANV = @MANV;

END

GO

-- (d)  SP_INSERT_BANGDIEM
-- Stored dùng để nhập bảng điểm của từng sinh viên
CREATE PROCEDURE SP_INSERT_BANGDIEM
    @MASV VARCHAR(20),
    @MAHP VARCHAR(20),
    @DIEM FLOAT,
    @MANV VARCHAR(20)
AS
BEGIN
    DECLARE @PUBKEY VARCHAR(20)
    
    -- Lấy khóa công khai của nhân viên
    SELECT @PUBKEY = PUBKEY FROM NHANVIEN WHERE MANV = @MANV
    
    -- Mã hóa điểm bảng Public Key
    DECLARE @ENCRYPTED_DIEM VARBINARY(MAX)
    SET @ENCRYPTED_DIEM = ENCRYPTBYKEY(KEY_GUID(@PUBKEY), CAST(@DIEM AS NVARCHAR))

    -- Luu vào bảng
    INSERT INTO BANGDIEM (MASV, MAHP, DIEMTHI)
    VALUES (@MASV, @MAHP, @ENCRYPTED_DIEM)
END

GO

